-- ShopWise - schéma relationnel PostgreSQL 16
-- Les prix sont figés dans SALE_LINES afin de préserver l'historique des ventes.

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total NUMERIC(14, 2) NOT NULL CHECK (total >= 0),
    sold_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL
);

CREATE TABLE sale_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 9999),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price > 0),
    line_total NUMERIC(14, 2) NOT NULL CHECK (line_total = unit_price * quantity),
    CONSTRAINT fk_sale_lines_sale FOREIGN KEY (sale_id)
        REFERENCES sales(id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_lines_product FOREIGN KEY (product_id)
        REFERENCES products(id) ON DELETE RESTRICT,
    CONSTRAINT uq_sale_product UNIQUE (sale_id, product_id)
);

CREATE INDEX idx_sales_sold_at ON sales (sold_at DESC, id DESC);
CREATE INDEX idx_sale_lines_product ON sale_lines (product_id);

INSERT INTO products (name, description, price) VALUES
    ('iPhone 15', 'Latest Apple smartphone', 999.99),
    ('Samsung Galaxy S24', 'Latest Samsung smartphone', 899.99),
    ('MacBook Pro 16"', 'Apple laptop', 2499.99),
    ('Dell XPS 13', 'Dell ultrabook', 1299.99);
